apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: retail-app-maintenance
  title: Retail App Maintenance
  description: Maintenance documentation
  tags:
    - docs
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/eng-squirrel]
  service: retail
  uri: https://www.notion.so/opencontext/Retail-App-Maintenance-49a977c54d074d1aae70eea154a1680e
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: retail-app-threat-model
  title: Retail App Threat Model
  description: Threat Model documentation
  tags:
    - security
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/eng-squirrel]
  service: retail
  uri: https://www.notion.so/opencontext/Retail-App-Threat-Model-a02f5c6c4ee24400a94bf8953e420387
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: retail-app-migration-plan
  title: Retail App Migration Plan
  description: Migration Plan documentation
  tags:
    - planning
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/prod-squirrel]
  service: retail
  uri: https://www.notion.so/opencontext/Retail-App-Migration-Plan-300557d741b34c6d87993f1c31e7130a
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: retail-app-ownership
  title: Retail App Service Ownership
  description: Service Ownership documentation
  tags:
    - docs
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/prod-squirrel]
  service: retail
  uri: https://www.notion.so/opencontext/Retail-App-Service-Ownership-Doc-6361695aea6f443ab78ad49926258f21
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: PlatformComponent
metadata:
  namespace: scatter-ly
  name: retail-vm
  description: Blue Sky / Retail virtual machine
  links:
    - url: https://example.com/cloud
      title: Cloud Console
      icon: cloud
    - url: https://example.com/dashboard
      title: Retail VM Dashboard
      icon: dashboard
  annotations:
    pagerduty.com/service-id: 'P2S21AB'
spec:
  type: vm
  subtype: micro
  lifecycle: production
  owner: [scatter-ly/it-ops]
  platform: [scatter-ly/retail]
  datacenter: [scatter-ly/aws, scatter-ly/gcp]
  dependencyOf: ['code-component:scatter-ly/retail-app', 'code-component:scatter-ly/retail-backend']
  priority: 1
  sla: 24x7
---
#apiVersion: opencontext.com/v1alpha1
#kind: PlatformComponent
#metadata:
#  namespace: scatter-ly
#  name: retail-dns
#  description: Blue Sky / Retail DNS
#  links:
#    - url: https://example.com/dns-docs
#      title: Retail DNS docs
#      icon: docs
#  annotations:
#    pagerduty.com/integration-key: 'PAGERDUTY_INTEGRATION_KEY'
#spec:
#  type: dns
#  lifecycle: production
#  owner: [scatter-ly/it-ops]
#  platform: [scatter-ly/retail]
#  datacenter: [scatter-ly/gcp]
#  dependencyOf:
#    [
#      'code-component:scatter-ly/retail-app',
#      'code-component:scatter-ly/retail-backend',
#    ]
#  priority: 1
#  sla: 24x7
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  namespace: scatter-ly
  name: retail-app-bb43745-sbom-spdx.json
  title: retail-app-bb43745-sbom-spdx.json
  links:
    - url: https://github.com/scatter-ly/retail-app/releases/download/v0.3.1/retail-app-bb43745-sbom-spdx.json
      title: retail-app-bb43745-sbom-spdx.json
    - url: https://github.com/scatter-ly/retail-app/actions/runs/6580262013
      title: GitHub Action Run 6580262013
  annotations:
    github.com/project-slug: scatter-ly/retail-app
spec:
  type: sbom
  uri: https://github.com/scatter-ly/retail-app/releases/download/v0.3.1/retail-app-bb43745-sbom-spdx.json
  lifecycle: production
  owner:
    - scatter-ly/alchen99
  dependsOn:
    - codecomponent:scatter-ly/retail-app

