apiVersion: opencontext.com/v1alpha1
kind: CodeComponentSidecar
metadata:
  name: retail-app-extras
spec:
  codecomponent: scatter-ly/retail-app
  platform: retail
  lifecycle: production
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  name: retail-app-maintenance
  title: Retail App Maintenance
  description: Maintenance documentation
  tags:
    - docs
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/eng-squirrel]
  platform: retail
  uri: https://www.notion.so/opencontext/Retail-App-Maintenance-49a977c54d074d1aae70eea154a1680e
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  name: retail-app-threat-model
  title: Retail App Threat Model
  description: Threat Model documentation
  tags:
    - security
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/eng-squirrel]
  platform: retail
  uri: https://www.notion.so/opencontext/Retail-App-Threat-Model-a02f5c6c4ee24400a94bf8953e420387
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  name: retail-app-migration-plan
  title: Retail App Migration Plan
  description: Migration Plan documentation
  tags:
    - planning
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/prod-squirrel]
  platform: retail
  uri: https://www.notion.so/opencontext/Retail-App-Migration-Plan-300557d741b34c6d87993f1c31e7130a
  dependsOn: [code-component:scatter-ly/retail-app]
---
apiVersion: opencontext.com/v1alpha1
kind: AuxComponent
metadata:
  name: retail-app-ownership
  title: Retail App Service Ownership
  description: Service Ownership documentation
  tags:
    - docs
spec:
  type: document
  lifecycle: production
  owner: [scatter-ly/prod-squirrel]
  platform: retail
  uri: https://www.notion.so/opencontext/Retail-App-Service-Ownership-Doc-6361695aea6f443ab78ad49926258f21
  dependsOn: [code-component:scatter-ly/retail-app]
