name: Creates various artifact yaml
on:
  pull_request:
  workflow_dispatch:

jobs:
  check_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-image-artifact-yaml
        name: Create image artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: image
          url: projects/debian-cloud/global/images/debian-11-bullseye-v20221206
      - name: Check image results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-image-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-image-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-image-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-image-artifact-yaml.outputs.filename }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: image-artifact
          path: ${{ steps.create-image-artifact-yaml.outputs.filename }}

  check_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-container-artifact-yaml
        name: Create container artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: container
          url: us-docker.pkg.dev/vpc-host-nonprod-345521/np-docker/scatterly/retail-app:v0.3.1
      - name: Check container results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-container-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-container-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-container-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-container-artifact-yaml.outputs.filename }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: retail-container-artifact
          path: ${{ steps.create-container-artifact-yaml.outputs.filename }}

  check_container_long:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-container-long-artifact-yaml
        name: Create container artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: container
          url: us-docker.pkg.dev/vpc-host-nonprod-345521/np-docker/scatterly/pretty-army-energy-brisk-hotel-grass-desert-talk-hat-moon-leopard-model:latest
      - name: Check container results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-container-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-container-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-container-long-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-container-long-artifact-yaml.outputs.filename }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: long-container-artifact
          path: ${{ steps.create-container-long-artifact-yaml.outputs.filename }}

  check_sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-sbom-artifact-yaml
        name: Create sbom artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: sbom
          url: https://github.com/scatter-ly/retail-app/releases/download/v0.1.6/spdx-4fff744e-abb9-4585-964b-21ac837cbb8b.spdx.json
      - name: Check sbom results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-sbom-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-sbom-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-sbom-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-sbom-artifact-yaml.outputs.filename }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: sbom-artifact
          path: ${{ steps.create-sbom-artifact-yaml.outputs.filename }}

  check_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-package-artifact-yaml
        name: Create package artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: package
          url: https://registry.npmjs.org/@octokit/rest/-/rest-19.0.3.tgz#b9a4e8dc8d53e030d611c053153ee6045f080f02
      - name: Check package results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-package-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-package-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-package-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-package-artifact-yaml.outputs.filename }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: package-artifact
          path: ${{ steps.create-package-artifact-yaml.outputs.filename }}

  check_output_dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-sbom2-artifact-yaml
        name: Create sbom artifact YAML
        uses: opencontextinc/create-artifact-yaml@v1
        with:
          type: sbom
          url: https://github.com/scatter-ly/retail-app/releases/download/v0.1.6/spdx-4fff744e-abb9-4585-964b-21ac837cbb8b.spdx.json
          directory: sbom
      - name: Check sbom results
        shell: bash
        run: |
          echo "Create artifact yaml filename is ${{ steps.create-sbom2-artifact-yaml.outputs.filename }}"
          echo "Create artifact yaml directory is ${{ steps.create-sbom2-artifact-yaml.outputs.directory }}"
          cat ${{ steps.create-sbom2-artifact-yaml.outputs.directory }}/*
          tar tvfz ${{ steps.create-sbom2-artifact-yaml.outputs.filename }}

