name: Test docker action
on:
  release:
    types: [created]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: scatter-ly/test-action@main
        with:
          type: sbom
          url: http://example.com
      - name: Check for file
        run: ls -l
