name: Upload SBOM and artifact context on release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: check-prereqs
        name: Check pre-requisites
        shell: bash
        run: |
          if [[ ${GITHUB_EVENT_NAME} != "release" ]]; then 
            echo "ERROR: This GitHub action only supports the release event!"
            exit 1
          fi
          shortSHA=$(echo $GITHUB_SHA | head -c7)
          repoName=$(basename $GITHUB_REPOSITORY)
          sbomFilename="${repoName}-${shortSHA}-sbom-spdx.json"
          releaseHtmlUrl=$(jq -r '.release.html_url' $GITHUB_EVENT_PATH)
          releaseTag=$(basename $releaseHtmlUrl)
          sbomUrl="${releaseHtmlUrl%%/releases/*}/releases/download/${releaseTag}/${sbomFilename}"
          echo "sbomFilename=${sbomFilename}" >> "$GITHUB_OUTPUT"
          echo "sbomUrl=${sbomUrl}" >> "$GITHUB_OUTPUT"
      - id: generate-sbom
        name: Generate SBOM
        uses: advanced-security/sbom-generator-action@v0.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - id: upload-sbom-release
        name: Upload SBOM as release artifact
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: ${{ steps.check-prereqs.outputs.sbomFilename }}
          path: ${{ steps.generate-sbom.outputs.fileName }}
          repo-token: ${{ github.token }}
          content-type:  application/json
      