name: Upload release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - id: upload-sbom
        name: Upload SBOM for Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.sbom.outputs.fileName }}

      - id: generate-artifact-context
        name: Generate Artifact Context
        uses: scatter-ly/artifact-context@v2.1
        with:
          artifact-type: SBOM
          url: ${{ fromJSON(steps.upload-sbom.outputs.assets)[0].browser_download_url }}

      - uses: actions/upload-artifact@v3.1.0
        with: 
          path: ${{steps.generate-artifact-context.outputs.filename }}
          name: artifact-context
