name: Upload release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload SBOM for Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.sbom.outputs.fileName }}
